### PR TITLE
Support username & password as ENV variables

### PR DESCRIPTION
**Pull request by mattjcline**
Hi, I'm hoping to merge this to allow more automated log-in when using this module. 
It also happens to fix the issue I filed. Happy to separate the two if you prefer. 
Cheers!

### CODE REVIEW

**Comment by itzmestar** [comment]
Credentials were entered via console for the purpose to avoid storing password in plain text.
But indeed, this is a nice feature to add which gives user the option to fully automate the flow.

Although I would prefer reading the credentials from system env variables rather than from .env file.

**Comment by mattjcline** [comment]
Thankfully, the .env file is optional. The `os.environ.get()` calls will check against env variables as well. 

```
~/dev/Octoparse/octoparse   add-dotenv  octoparse                                                                                 ✔  9245  08:07:39
 $ mv .env .env.BAK
 ~/dev/Octoparse/octoparse   add-dotenv ?  octoparse                                                                               ✔  
9247  08:08:02
 $ export OCTOPARSE_USERNAME=[MYUSERNAME]
 ~/dev/Octoparse/octoparse   add-dotenv ?  octoparse                                                                               ✔  9248  08:08:13
 $ export OCTOPARSE_PASSWORD=[MYPASSWORD]
 ~/dev/Octoparse/octoparse   add-dotenv ?  octoparse                                                                               ✔  9251  08:09:09
 $ python
Python 3.8.5 (default, Jul 21 2020, 10:42:08)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import octoparse
>>> octoparse.Octoparse()
<octoparse.Octoparse object at 0x106d64040>
>>> octo = _ ; octo.list_all_task_groups()
[{'taskGroupId': 365661, 'taskGroupName': 'MyGroup'},]
```

**Comment by mattjcline** [comment]
@itzmestar hey, what're your thoughts on merging this? I will close as a wontfix if you don't plan on merging.

**Comment by itzmestar** [comment]
Haven't got chance to review it yet.

**Comment by itzmestar** [comment]
@mattjcline can you please test again if .env is working fine?

**Comment by mattjcline** [comment]
it doesn't work from the project root but i put a .env file in the octoparse dir and it's working.
setting general ENV variables should work too. 

```
 ~/dev/Octoparse   add-dotenv  octoparse                                                                                           ✔  9983  10:26:22
 $ ls
LICENSE   README.md octoparse setup.py
 ~/dev/Octoparse   add-dotenv  octoparse                                                                                           ✔  9984  10:26:57
 $ python
Python 3.8.6 (default, Oct 27 2020, 08:57:44)
[Clang 12.0.0 (clang-1200.0.32.21)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from octoparse import octoparse
>>> octo = octoparse.Octoparse()
Enter Octoparse Username: Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mcline/dev/Octoparse/octoparse/octoparse.py", line 94, in __init__
    self._read_token_file()
  File "/Users/mcline/dev/Octoparse/octoparse/octoparse.py", line 108, in _read_token_file
    self.log_in()
  File "/Users/mcline/dev/Octoparse/octoparse/octoparse.py", line 150, in log_in
    username = input("Enter Octoparse Username: ")
EOFError
 ~/dev/Octoparse   add-dotenv ?  octoparse                                                                                         ✔  9985  10:27:31
 $ cd octoparse
 ~/dev/Octoparse/octoparse   add-dotenv ?  octoparse                                                                               ✔  9986  10:27:34
 $ python
Python 3.8.6 (default, Oct 27 2020, 08:57:44)
[Clang 12.0.0 (clang-1200.0.32.21)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from octoparse import Octoparse
>>> octo = Octoparse()
>>> octo
<octoparse.Octoparse object at 0x10ffafd60>
```

**Pull request merged**
